version: "3.2"
services:
  apache:
    build: './php/'
    depends_on:
      - mysql
    networks:
      - frontend
      - backend
    ports:
      - 80:80
    volumes:
      - ./public_html/:/var/www/html/
      - ./private_files/:/var/private/
    environment:
      PMA_HOST: mysql
  mysql:
    image: mysql:5.6.40
    networks:
      - backend
    ports:
      - 3200:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    networks:
      - backend
    links:
      - mysql
    ports:
      - 8081:80
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
  python:
    build: './python/'
    depends_on:
      - mysql
    networks:
      - backend
    links:
      - mysql:mysql
    ports:
      - 5001:5000
    volumes:
      - ./python/:/python/
    environment:
      PMA_HOST: mysql
    restart: on-failure
networks:
  frontend:
  backend: