swagger: "2.0"
info:
  description: "This is the swagger file that goes with our Meadow Monitor server"
  version: "1.0.0"
  title: "Swagger REST Article"
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

# Paths supported by the server application
paths:
  /emb/{device_id}/desired/:
    get:
      operationId: "server.emb.desired"
      tags:
        - emb
      summary: "Fetch the desired values for the embedded device's plant"
      parameters:
        - in: path
          name: device_id
          required: true
          type: integer
          minimum: 1
          description: "Device ID"
      responses:
        200:
          description: "Successful desired values json operation"
          schema:
            type: object
            properties:
              #              plant_type:
              #                type: "string"
              moisture:
                type: string
              light:
                type: string
              temperature_min:
                type: number
#              ph_min:
#                type: number
#              ph_max:
#                type: number
              ph:
                type: number
        404:
          description: "Device not found."

  /emb/{device_id}/log/:
    post:
      operationId: "server.emb.log"
      tags:
        - emb
      summary: "Log current sensor values for the embedded device's plant"
      parameters:
        - in: path
          name: device_id
          required: true
          type: integer
          minimum: 1
          description: "Device ID"
        - in: body
          name: values
          required: true
          schema:
            type: object
            properties:
              #              date:
              #                type: string
              #              species:
              #                type: string
              light:
                type: number
              moisture:
                type: number
              ph:
                type: number
              temp:
                type: number
      responses:
        201:
          description: "Successful sensor value log. Returns ID of new data object."
        404:
          description: "Device not found."

  /webapp/{device_id}/history/:
    get:
      operationId: "server.webapp.history"
      tags:
        - webapp
      summary: "Fetch historical sensor data for an embedded device"
      parameters:
        - in: path
          name: device_id
          required: true
          type: integer
          minimum: 1
          description: "Device ID"
        - in: query
          name: rows
          required: false
          type: integer
          default: 5
          description: "number of rows to fetch"
      responses:
        200:
          description: "Successful historical data fetch"
          schema:
            type: array
            items:
              properties:
                device_id:
                  type: integer
                date:
                  type: string
                species:
                  type: string
                light:
                  type: number
                moisture:
                  type: number
                ph:
                  type: number
                temp:
                  type: number
        204:
          description: "Device has no history."
        404:
          description: "Device not found."

  /webapp/{device_id}/plant:
    get:
      operationId: "server.webapp.get_plant"
      tags:
        - webapp
      summary: "Fetch current plant for an embedded device"
      parameters:
        - in: path
          name: device_id
          required: true
          type: integer
          minimum: 1
          description: "Device ID"
      responses:
        200:
          description: "Successful plant type fetch"
          schema:
            type: string
        204:
          description: "Device has no plant set"
        404:
          description: "Device not found."

  /webapp/{device_id}/plant/change:
    post:
      operationId: "server.webapp.change_plant"
      tags:
        - webapp
      summary: "Change the plant species of the device"
#      consumes:
#        - "text/plain"
      parameters:
        - in: path
          name: device_id
          required: true
          type: integer
          minimum: 1
          description: "Device ID"
        - in: query
          name: species_id
          required: true
          type: integer
          description: "The new plant species ID to change to"
      responses:
        200:
          description: "Successful update"
          schema:
            type: string

  /webapp/{device_id}/override:
    post:
      operationId: "server.webapp.override_values"
      tags:
        - webapp
      summary: "Override the device target values"
#      consumes:
#        - "text/plain"
      parameters:
        - in: path
          name: device_id
          required: true
          type: integer
          minimum: 1
          description: "Device ID"
        - in: body
          name: values
          required: true
          schema:
            type: object
            properties:
              moisture:
                type: string
                description: "ideal moisture (LOW, HIGH, MEDIUM)"
              temperature:
                type: number
                description: "ideal temperature (°F)"
#        - in: body
#          name: species
#          required: false
#          schema:
#            type: integer
#          description: "The new plant species to change to"
#        - in: body
#          name: moisture
#          required: false
#          schema:
#            type: number
#          description: "The new target moisture to change to"
#        - in: body
#          name: temperature
#          required: false
#          schema:
#            type: number
#          description: "The new target temperature to change to"
      responses:
        200:
          description: "Successful update"
          schema:
            type: string

  /webapp/{user_id}:
    get:
      operationId: "server.webapp.list_devices"
      tags:
        - webapp
      summary: "List a user's owned device IDs and plants"
      parameters:
        - in: path
          name: user_id
          required: true
          type: integer
          minimum: 1
          description: "User ID"
      responses:
        200:
          description: "Successful device list fetch."
          schema:
            type: array
            items:
              properties:
                device_id:
                  type: integer
                plant_type:
                  type: string
                label:
                  type: string
        204:
          description: "User has no devices."
        404:
          description: "User not found."

  /webapp/{user_id}/add:
    put:
      operationId: "server.webapp.add_device"
      tags:
        - webapp
      summary: "Add a new device for a user"
      parameters:
        - in: path
          name: user_id
          required: true
          type: integer
          minimum: 1
          description: "User ID"
        - in: body
          name: values
          required: false
          schema:
            type: object
            properties:
              label:
                type: string
      responses:
        201:
          description: "Successful device add. Returns the new device ID."
          schema:
            type: integer

  /webapp/search:
    get:
      operationId: "server.webapp.search"
      tags:
        - webapp
      summary: "Search plants database for a partial term"
      parameters:
        - in: query
          name: search_term
          type: string
          required: true
          description: "Partial search term"
      responses:
        200:
          description: "Found plants"
          schema:
            type: array
            items:
              properties:
                id:
                  type: integer
                scientific_name:
                  type: string
                common_name:
                  type: string
                complete_data:
                  type: boolean
        204:
          description: "No plants found"